on:
  push:
    branches:
    - main
    - master
jobs:
  video:
    name: Record the video
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Deps
        run: |
          sudo apt-get update && sudo apt-get install -y \
            curl \
            git \
            make \
            wget \
            unzip \
            gnupg \
            xvfb \
            bash \
            pulseaudio \
            ffmpeg \
            fonts-noto-core \
            fonts-noto-cjk \
            language-pack-zh-hans \
            fonts-droid-fallback ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming

          wget -q 'https://github.com/macchrome/linchrome/releases/download/v131.6778.244-M131.0.6778.244-r1368529-portable-ungoogled-Lin64/ungoogled-chromium_131.0.6778.244_1.vaapi_linux.tar.xz'
          tar xvf ungoogled-chromium_131.0.6778.244_1.vaapi_linux.tar.xz
          pwd
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
      - name: Install Deps
        run: npm i
      - name: Run Pulseaudio
        run: |
          set +x
          sudo adduser root pulse-access
          sudo adduser $(whoami) pulse-access
          pulseaudio --start -D --verbose --exit-idle-time=-1 --disallow-exit
          pactl load-module module-null-sink sink_name="grab" sink_properties=device.description="monitorOUT"
          pactl list short sources
      - name: Record video
        run: |
          cd src
          npx ts-node t.ts
          ls -lah
          cd ..
          ls -lah

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          # Artifact name
          name: screen.webm
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/work/time-recorder/happy-date/screen.webm
